apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: firelink-proxy

objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: firelink-proxy
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: firelink-proxy
    template:
      metadata:
        labels:
          app: firelink-proxy
      spec:
        containers:
        - name: firelink-proxy
          image: your-docker-image:latest
          ports:
          - containerPort: 8000
        - name: oauth-proxy 
          args:
            - -provider=openshift
            - -https-address=:8888
            - -http-address=
            - -email-domain=*
            - -upstream=http://localhost:8000
            - -tls-cert=/etc/tls/private/tls.crt
            - -tls-key=/etc/tls/private/tls.key
            - -cookie-secret-file=/etc/proxy/secrets/session_secret
            - -openshift-service-account=firelink-proxy
            - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            - -skip-auth-regex=^/metrics
            - -pass-user-headers=true
          image: quay.io/openshift/origin-oauth-proxy:4.14
          imagePullPolicy: IfNotPresent
          ports:
            - name: oauth-proxy
              containerPort: 8888    
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/tls/private
              name: secret-firelink-proxy-tls
            - mountPath: /etc/proxy/secrets
              name: secret-firelink-proxy-proxy

- apiVersion: v1
  kind: Service
  metadata:
    name: firelink-proxy
    service.alpha.openshift.io/serving-cert-secret-name: firelink-proxy-tls
    labels:
      name: firelink-proxy
  spec:
    selector:
      app: firelink-proxy
    ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: firelink-proxy

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: firelink-proxy
  spec:
    to:
      kind: Service
      name: firelink-proxy
